### ISSUE TITLE
To add to the documentation

### ISSUE THREAD

**Issue by bdrayer** [oliviermaridat/kanboard-sqlite2mysql#1]
Hi,

I have used your script to make the backup but it has not work because I didn't have "zip" on my Debian install (because I use TAR and GUNZIP mostly and only have UNZIP to allow me to decompress something).

It would perhaps be a good idea to add to the documentation that ZIP is also needed

Best regards

**Comment by bdrayer** [comment]
Hi,

You have write many times on you doc kanbord and not kanboard

Best regards

**Comment by bdrayer** [comment]
It will be good also to add that if people want to import the SQL script into MYSQL, they will need to import the Kanboard SQL schema first

**Comment by magsilva** [comment]
Instead of importing the schema, a better option is to access Kanboard with an empty MySQL database. That should create all the required tables, easing the import of the SQL data.
