### ISSUE TITLE
Does it work with 1.1.0? 

### ISSUE THREAD

**Issue by aslmx** [oliviermaridat/kanboard-sqlite2mysql#10]
sorry for this non-issue but rather question... 

I upgraded my sqlite based kanboard instance to the latest stable version, 1.1.0.
On another server i setup kanboard to use mysql and also updated to the last version.

Then i ran the export script and tried to import it with mysql. 

Apparently the script fails with multiple fields that are not existing.
- predefined_email (projects)
- is_admin (users)

i have tried to sort out these differences in db schema manually but i gave up after some time. 

Has someone succesfully migrated from sqlite to mysql recently with 1.1.0?

I have the feeling the db-schema is not equal between sqlite and mysql.

**Comment by oliviermaridat** [comment]
Since the creation of this script, some fields have been removed (or renamed) in Kanboard db. This causes the script to fail. 
The script shall be modified to ignore unexisting fields.

**Comment by aslmx** [comment]
Thanks for your quick reply.
Is there any plans to make this working again soon?

**Comment by oliviermaridat** [comment]
I will most certainly not have time for this, sorry.
Do not hesitate to propose a PR about this.

**Comment by oliviermaridat** [comment]
The last version has been tested for kanboard 1.1.1!
