### ISSUE TITLE
Update for SQlite 116 to MySQL schema 126

### ISSUE THREAD

**Issue by olberger** [oliviermaridat/kanboard-sqlite2mysql#12]
I've tested porting from SQLite schema version 116 to MySQL schema version 126 (kanboard 1.1.1), and came up with the following changes: https://github.com/olberger/kanboard-sqlite2mysql/commit/7d871a051d4d2985937b8c28e6b9fa2ef9ef4183

It is rather untested so your mileage may vary.

Feel free to merge ;-)

**Comment by oliviermaridat** [comment]
PR merged! Thanks.
