### ISSUE TITLE
migration kanboard 1.2.4 failed

### ISSUE THREAD

**Issue by jcpreaux** [oliviermaridat/kanboard-sqlite2mysql#14]
Hi,
i've tried to migrate sqlite to mysql with kanboard 1.2.4 without any success :

#######
sudo ./kanboard-sqlite2mysql.sh /var/sites/kanboard kanboard -h localhost -u kanboard -p
Enter password:

# Create MySQL data dump from SQLite database
done
check db-mysql.sql
# Generate schema in the MySQL database using Kanboard
done
# Fill the MySQL database with the SQLite database data
Warning: Using a password on the command line interface can be insecure.
ERROR 1054 (42S22) at line 159: Unknown column 'date_board' in 'field list'
FAILLURE
######

Informations :
SQLite v3.11.0
MySQL Percona 5.6.40-84.0
Kanboard 1.2.4 (with all plugins uninstalled)
OS Ubuntu 17.0.4-LTS  Linux 4.4.0-128-generic.

Thanks for your job !

**Comment by oliviermaridat** [comment]
Hi!
Did you use plugins and remove them? "date_board" may be in a plugin.

Anyway, you can check between Kanboard v1.2.2 (migration worked with this script) and your v1.2.4 what has changed on the database around "date_board". Apparently "date_board" is missing in the v1.2.4 schema.

**Comment by jcpreaux** [comment]
Hi,
The date_board field is from TaskBoard plugin
https://github.com/kanboard/plugin-task-board-date/blob/master/Schema/Sqlite.php

And the field was not deleted from the table ('cause not null) when i deleted the plugin.

**Comment by jcpreaux** [comment]
Migration is ok after i've deleted fields and tables added by plugins and not dropped while uninstalling them.

**Comment by oliviermaridat** [comment]
Thanks for the feedback. That is exactly what I had in mind ;-)
