### ISSUE TITLE
ERROR 1062 (23000) at line 57: Duplicate entry 'Work in Progress-1' for key 'idx_title_project'

### ISSUE THREAD

**Issue by Skyridr** [oliviermaridat/kanboard-sqlite2mysql#19]
Using Ubuntu 16.04, MariaDB 10.3.14 and latest kanboard 1.2.9

Apparently when I attempt to import my sqlite file into the database using the last step, getting a duplicate entry error:

> check db-mysql.sql
> Generate schema in the MySQL database using Kanboard
> done
> Fill the MySQL database with the SQLite database data
> ERROR 1062 (23000) at line 57: Duplicate entry 'Work in Progress-1' for key 'idx_title_project'
> FAILLURE

Here is the list of INSERTS:

![image](https://user-images.githubusercontent.com/6794064/55956283-e4b38a00-5c63-11e9-81e6-36bca054d7d9.png)

Highlighted = line 57 (error line in terminal)

Was an empty database btw :)

Regards,
Skyrider

**Comment by Skyridr** [comment]
Been 4 months, a reply would be appreciated.

**Comment by oliviermaridat** [comment]
It seems your project "3" has three times the colum "Work in progress".

**Comment by Skyridr** [comment]
Not that I can see:

![image](https://user-images.githubusercontent.com/6794064/63708318-5b78aa80-c834-11e9-8dc5-1f44b153bb5c.png)

Work in Progress is used in multiple projects though, but none of them contains duplicates.

**Comment by Skyrid3r** [comment]
Even if I rename the stuff, and attempt to do so again.. I'm getting:

ERROR 1060 (42S21) at line 1: Duplicate column name 'is_admin'
