### ISSUE TITLE
Success after minor problems

### ISSUE THREAD

**Issue by bdrayer** [oliviermaridat/kanboard-sqlite2mysql#3]
Hi,

After installing ZIP, creating a database and import the kanboard SQL schema into it, correction SQL file to replace /r`) by`), making character encoding corrections it has worked for me on Debian Jessie, with MariaDB 10.0.23, SQLite version 2.8.17 and kanboard 1.0.27.

Thanks a lot

Best regards

**Comment by oliviermaridat** [comment]
Thank you for your feedback, it is really appreciated!

I will add something to choose between zip and tar, and replace `/r )` by `)`.
