### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by SimonOffermann** [oliviermaridat/kanboard-sqlite2mysql#4]
At first I want to thank you for the Idea of making such a script. As I also fell for the "well, how bad can sqlite be"-Situation, I hope, I can migrate with your help. Sadly, it didn't work a planned in v1.0.28

Here's the output, slightly modified with placeholders for security reasons. In the original I saw the correct path when it says so and my password wasn't "The right one!" ;) But I am pretty sure these messages aren't directly related to my data. I used the out-of-he box KanBoard 1.0.28 without any modification "under the bonnet".
------------begin
:~/kanboard-sqlite2mysql > kanboard-sqlite2mysql.sh /path database -h host -u user -p
Enter password:
The right one! ;)
# Create MySQL data dump from SQLite database

done
check db-mysql.sql
# Generate schema in the MySQL database using Kanboard

mv: cannot stat `[correct path]/htdocs/KanBoard/config.php': No such file or directory
X-Powered-By: PHP
Content-type: text/html

<br />
<b>Warning</b>:  Unexpected character in input:  '\' (ASCII=92) state=1 in <b>[correct path]/htdocs/KanBoard/app/common.php</b> on line <b>5</b><br />
<br />
<b>Parse error</b>:  syntax error, unexpected T_STRING in <b>[correct path]/htdocs/KanBoard/app/common.php</b> on line <b>5</b><br />
mv: cannot stat `[correc path]/htdocs/KanBoard/config_tmp.php': No such file or directory
FAILLURE
# Fill the MySQL database with the SQLite database data

ERROR 1146 (42S02) at line 1: Table 'database.users' doesn't exist
FAILLURE
-------------the end

Any Idea how to fix this?

Yours sincerly
Simon

**Comment by oliviermaridat** [comment]
Hi,

This 

> mv: cannot stat `[correct path]/htdocs/KanBoard/config.php': No such file or directory

and this

> mv: cannot stat `[correc path]/htdocs/KanBoard/config_tmp.php': No such file or directory

are actually (unimportant) bugs. I need to fix them by checking if the "config.php" exists or not. Even if it fails, this is not an issue for the whole process.

However, this

> Warning: Unexpected character in input: '\' (ASCII=92) state=1 in [correct path]/htdocs/KanBoard/app/common.php on line 5
> Parse error: syntax error, unexpected T_STRING in [correct path]/htdocs/KanBoard/app/common.php on line 5

is really strange... Is your Kanboard instance working? These lines are PHP errors in Kanboard codes... I will try to test on a raw 1.0.28.

And to finish, the finale step cannot work without the second. Which explains the last failure.

**Comment by SimonOffermann** [comment]
The instance is working great-ish, it has poor performance which could be connected to SQLite, but it is fully functional. The only non-standard thing at all is that there are no .htaccess-files, eeverything else is just as it downloaded.

The File in Question Starts with:

<?php

require **DIR**.'/../vendor/autoload.php';

$dbUrlParser = new PicoDb\UrlParser();                              //this is line 5

if ($dbUrlParser->isEnvironmentVariableDefined()) {
    $dbSettings = $dbUrlParser->getSettings();

```
define('DB_DRIVER', $dbSettings['driver']);
define('DB_USERNAME', $dbSettings['username']);
define('DB_PASSWORD', $dbSettings['password']);
define('DB_HOSTNAME', $dbSettings['hostname']);
define('DB_PORT', $dbSettings['port']);
define('DB_NAME', $dbSettings['database']);
```

}

**Comment by hbondoc** [comment]
Hi Sir i try the script is working but the  attachment is missing..

**Comment by oliviermaridat** [comment]
@hbondoc "the attachment"? Sorry, but I did not see what you mean.

**Comment by hbondoc** [comment]
@oliviermaridat " I Mean the document or image attached from the  server.. when i migrate using the script was successful but the attachment or task was missing...

**Comment by hbondoc** [comment]
@oliviermaridat Any help.. still the existing attachment not imported on mysql database.

**Comment by oliviermaridat** [comment]
Hi @hbondoc . This script is exporting only the database, not the attached files. Normally the link to the attached documents are preserved from the SQLite to the MySQL database.

If you are using two instances of Kanboard, one with SQLite, and the other one with a MySQL database imported from SQLite with the script, you should manually copy you attached documents from the the first instance to the second one.
