### ISSUE TITLE
ERROR 1054 (42S22) at line 72: Unknown column 'date_board' in 'field list' and text encoding problem

### ISSUE THREAD

**Issue by Stepkaa** [oliviermaridat/kanboard-sqlite2mysql#6]
Hi! Thanks for the script :) But there are some problems like: 
ERROR 1054 (42S22) at line 72: Unknown column 'date_board' in 'field list'

Please, can you explain how to fix this? I suppose this problem won't be the only one. 

And one more: after migration there is an encoding problem. Since all stuff in the db was in russian, after export all I have is a bunch of weird symbols.

**Comment by Stepkaa** [comment]
ERROR 1054 solved: if you had "plugin-task-board-date" then do this: ALTER TABLE `tasks` ADD COLUMN `date_board` INT DEFAULT '0';

**Comment by oliviermaridat** [comment]
Thanks.
