### ISSUE TITLE
Worked with one small error.

### ISSUE THREAD

**Issue by tmkdev** [oliviermaridat/kanboard-sqlite2mysql#7]
mysql -h xxxxx -u kanboard -p -f kanboard < test.sql
Enter password:
ERROR 1832 (HY000) at line 5007: Cannot change column 'column_id': used in a foreign key constraint 'tasks_ibfk_2'

Application version: 1.0.34
PHP version: 7.0.9
PHP SAPI: fpm-fcgi
OS version: Linux 3.10.0-327.28.2.el7.x86_64
Database driver: mysql
Database version: 10.0.19-MariaDB-log

**Comment by oliviermaridat** [comment]
Thanks @tmkdev. How did you sovle this issue?

**Comment by magsilva** [comment]
I had the same problem here. The workaround was to disable foreign key checks.
