### ISSUE TITLE
ERROR 1054 alt line 16: Unknown column 'default_swimlane' in 'field list' FAILURE

### ISSUE THREAD

**Issue by wolfganghirsch** [oliviermaridat/kanboard-sqlite2mysql#9]
I want to convert the sqlite3-db to a mysql database, in debian.
When start with   >. ./kanboard-sqlite2mysql.sh /var/www/kanboard -o db-mysql.sql< 
after a while this error happens. 
Pelase, how could I fix it?

**Comment by wolfganghirsch** [comment]
Sorry I forgot this:

Application version: 1.0.41
PHP version: 5.4.45-0+deb7u2
PHP SAPI: apache2handler
OS version: Linux 3.2.0-4-amd64
Database driver: mysql
Database version: 5.6.35

**Comment by rajo** [comment]
+1 same problem here

**Comment by bmalynovytch** [comment]
I had the same issue and managed to migrate:
- create an empty MySQL db for Kanboard
- change `const VERSION = 122;` to `const VERSION = 121;` in `app/Schema/Mysql.php`
- call the Kanboard URL to trigger the db population
- import the generated dump to fill the empty tables
- change back `const VERSION = 121;` to `const VERSION = 122;` in `app/Schema/Mysql.php`
- comment the `Create new default swimlane` SQL calls in `app/Schema/Migration.php`
- call the Kanboard URL again to trigger the db update
- revert the `Create new default swimlane` commented SQL calls in `app/Schema/Migration.php`
- done.

**Comment by rajo** [comment]
@bmalynovytch thank you very much for figuring this out -- worked for me as well!

**Comment by popindavibe** [comment]
Hello, same issue for me as well.
Tried @bmalynovytch procedure but I nothing gets migrated for now... I'm running latest stable.

**Comment by popindavibe** [comment]
I had another issue with `^M` characters appearing at the end of the lines but not only.
I ran, in following order:
```
fromdos kanboard.sql
sed -i -e "s/^M//" kanboard.sql
```
Now I could import almost everything (only last line failed) by commenting all SQL modifs in **app/Schema/Mysql.php**
```
function version_122(PDO $pdo)
{
    migrate_default_swimlane($pdo);

    //$pdo->exec('ALTER TABLE `projects` DROP COLUMN `default_swimlane`');
    //$pdo->exec('ALTER TABLE `projects` DROP COLUMN `show_default_swimlane`');
    //$pdo->exec('ALTER TABLE `tasks` MODIFY `swimlane_id` INT(11) NOT NULL;');
    //$pdo->exec('ALTER TABLE tasks ADD CONSTRAINT tasks_swimlane_ibfk_1 FOREIGN KEY (swimlane_id) REFERENCES swimlanes(id) ON DELETE CASCADE');
}
```
Last line of the import that failed was:
```
ALTER TABLE `tasks` CHANGE `column_id` `column_id` INT( 11 ) NOT NULL;
```
I could apply manually changes from version_122  into the database after import, however that last line is not compatible with foreign key:
```
ALTER TABLE `tasks` CHANGE `column_id` `column_id` INT( 11 ) NOT NULL;
ERROR 1832 (HY000): Cannot change column 'column_id': used in a foreign key constraint 'tasks_ibfk_2'
```
Is it okay or should I try to fix this? This line is part of version_74 update.

**Comment by oliviermaridat** [comment]
Normally, this PR should have fixed this issue automatically: https://github.com/olberger/kanboard-sqlite2mysql/commit/7d871a051d4d2985937b8c28e6b9fa2ef9ef4183
